<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Spring Boot Parent -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.3</version>
        <relativePath/>
    </parent>

    <!-- Project Information -->
    <groupId>io.github.mdaman45</groupId>
    <artifactId>queueforge</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>QueueForge</name>

    <description>
        AI-Powered Distributed Task Processing Platform
    </description>

    <url>https://github.com/Md-Aman45/queueforge</url>

    <!-- Properties -->
    <properties>

        <java.version>21</java.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <spring-cloud.version>2025.0.0</spring-cloud.version>

        <mapstruct.version>1.6.3</mapstruct.version>

        <lombok.version>1.18.38</lombok.version>

        <postgresql.version>42.7.7</postgresql.version>

        <testcontainers.version>1.21.3</testcontainers.version>

        <springdoc.version>2.8.9</springdoc.version>

    </properties>

    <!-- Spring Cloud BOM -->
    <dependencyManagement>

        <dependencies>

            <dependency>

                <groupId>org.springframework.cloud</groupId>

                <artifactId>spring-cloud-dependencies</artifactId>

                <version>${spring-cloud.version}</version>

                <type>pom</type>

                <scope>import</scope>

            </dependency>

        </dependencies>

    </dependencyManagement>

    <!-- Child Modules -->
    <modules>

        <!--
            shared
            services/job-service
            services/communication-worker
            services/document-worker
            services/media-worker
            services/cloud-worker
            services/ai-worker
            services/ai-service
            services/ml-service
        -->


        <module>shared</module>
        <module>services/job-service</module>

    </modules>

</project>